services:
  minio:
    image: minio/minio:latest
    ports:
      - "9090:9090"
      - "9000:9000"
    volumes:
      - ./minio:/data
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command:   minio server /data  --console-address ":9000" --address ":9090"

