services:
  postgres:
    image: postgres:latest
    container_name: MyPostgres
    volumes:
      - ./db_data:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - backend-network
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - 8000:8000
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
