from datetime import datetime
from typing import Optional

from pydantic import BaseModel, ConfigDict


class FileBase(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    filename: str
    file_location: str
    user_id: str
    course_id: Optional[str] = None


class FileCreate(BaseModel):
    """Schema for creating files - file_location is generated by the system"""
    model_config = ConfigDict(from_attributes=True)
    filename: str
    user_id: str
    course_id: Optional[str] = None


class FileResponse(FileBase):
    file_id: str
    timestamp: datetime
