# Backend CI Workflow
# This workflow builds and pushes a Docker image for the backend service to GitHub Container Registry.
# It runs on workflow dispatch or when called by another workflow.

name: Backend-Dev-CI

on:
  workflow_dispatch: # Allows manual triggering of the workflow, temporary exist for testing
  workflow_call:



# Configures this workflow to run every time a change is pushed to the branch called `release`.

# Defines two custom environment variables for the workflow. These are used for the Container registry domain, and a name for the Docker image that this workflow builds.
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/pastexam/backend

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  dev-build-and-push-image:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    steps:
      - name: run dev r-ci
        uses: ./.github/workflows/r-ci.yml
        with:
          isDev: true
          imageName: ${{ env.IMAGE_NAME }}
          REGISTRY: ${{ env.REGISTRY }}
      
      
