name: Dev backend workflow

on:
  workflow_dispatch:


jobs:
  trigger-backend-ci:
    uses: ./.github/workflows/backend-ci.yml

  trigger-backend-cd:
    uses: ./.github/workflows/backend-cd.yml
    with:
      runner-tag: dev
      docker-image-tag: ${{ github.head_ref || github.ref_name }}
