name: Dev frontend workflow

on:
  workflow_dispatch:

jobs:
  trigger-frontend-ci:
    uses: ./.github/workflows/frontend-ci.yml
  trigger-frontend-cd:
    needs: trigger-frontend-ci
    uses: ./.github/workflows/frontend-cd.yml
